<a href="https://colab.research.google.com/github/Sanjeev00001/Machine-Learning-1/blob/main/KM068_adult_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
dataset=pd.read_csv('/content/adult.csv', header=None, na_values=' ?')

In [ ]:
dataset.shape

(32561, 15)

In [ ]:
dataset.head()

0                  1       2           3   4                    5   \
0  39          State-gov   77516   Bachelors  13        Never-married   
1  50   Self-emp-not-inc   83311   Bachelors  13   Married-civ-spouse   
2  38            Private  215646     HS-grad   9             Divorced   
3  53            Private  234721        11th   7   Married-civ-spouse   
4  28            Private  338409   Bachelors  13   Married-civ-spouse   

                   6               7       8        9     10  11  12  \
0        Adm-clerical   Not-in-family   White     Male  2174   0  40   
1     Exec-managerial         Husband   White     Male     0   0  13   
2   Handlers-cleaners   Not-in-family   White     Male     0   0  40   
3   Handlers-cleaners         Husband   Black     Male     0   0  40   
4      Prof-specialty            Wife   Black   Female     0   0  40   

               13      14  
0   United-States   <=50K  
1   United-States   <=50K  
2   United-States   <=50K  
3   United-States   <=50K  
4            Cuba   <=50K

In [ ]:
dataset.columns=['age', 'workclass', 'wgt', 'edu', 'edu_num','marital_status', 'occ',
                 'relation', 'race', 'sex', 'gain', 'loss', 'hpw', 'country','income']

In [ ]:
dataset.isnull().sum()

age                  0
workclass         1836
wgt                  0
edu                  0
edu_num              0
marital_status       0
occ               1843
relation             0
race                 0
sex                  0
gain                 0
loss                 0
hpw                  0
country            583
income               0
dtype: int64

In [ ]:
from sklearn.impute import SimpleImputer
si=SimpleImputer(strategy='most_frequent')
dataset1=si.fit_transform(dataset)
dataset1=pd.DataFrame(dataset1)
print(dataset1.isna().sum())

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
dtype: int64


In [ ]:
dataset1.head()

0                  1       2           3   4                    5   \
0  39          State-gov   77516   Bachelors  13        Never-married   
1  50   Self-emp-not-inc   83311   Bachelors  13   Married-civ-spouse   
2  38            Private  215646     HS-grad   9             Divorced   
3  53            Private  234721        11th   7   Married-civ-spouse   
4  28            Private  338409   Bachelors  13   Married-civ-spouse   

                   6               7       8        9     10 11  12  \
0        Adm-clerical   Not-in-family   White     Male  2174  0  40   
1     Exec-managerial         Husband   White     Male     0  0  13   
2   Handlers-cleaners   Not-in-family   White     Male     0  0  40   
3   Handlers-cleaners         Husband   Black     Male     0  0  40   
4      Prof-specialty            Wife   Black   Female     0  0  40   

               13      14  
0   United-States   <=50K  
1   United-States   <=50K  
2   United-States   <=50K  
3   United-States   <=50K  
4            Cuba   <=50K

In [ ]:
cols=[1,3,5,6,7,8,9,13,14]
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for i in cols:
  dataset1[i]=le.fit_transform(dataset1[i])
print(dataset1.head())

   0   1       2   3   4   5   6   7   8   9     10 11  12  13  14
0  39   6   77516   9  13   4   0   1   4   1  2174  0  40  38   0
1  50   5   83311   9  13   2   3   0   4   1     0  0  13  38   0
2  38   3  215646  11   9   0   5   1   4   1     0  0  40  38   0
3  53   3  234721   1   7   2   5   0   2   1     0  0  40  38   0
4  28   3  338409   9  13   2   9   5   2   0     0  0  40   4   0


In [ ]:
target=dataset1[14]
input=dataset1.drop(columns=[14])
print(input.shape)
print(target.shape)

(32561, 14)
(32561,)


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train,y_test=train_test_split(input, target,test_size=0.25)
print(x_train.shape)
print(x_test.shape)

(24420, 14)
(8141, 14)


In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
xtrain_sc=sc.fit_transform(x_train)
xtest_sc=sc.transform(x_test)

In [ ]:
#### Perceptron
from sklearn.linear_model import Perceptron
p=Perceptron(penalty='l2')
p.fit(xtrain_sc, y_train)

Perceptron(penalty='l2')

In [ ]:
from sklearn.metrics import accuracy_score
train_pred=p.predict(xtrain_sc)
print("Training Accuracy:", accuracy_score(train_pred, y_train))

Training Accuracy: 0.7591318591318591


In [ ]:
test_pred=p.predict(xtest_sc)
print("Testing Accuracy:", accuracy_score(test_pred, y_test))

Testing Accuracy: 0.7696843139663432


In [ ]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(train_pred, y_train))

[[14501  1820]
 [ 4062  4037]]


In [ ]:
print(y_train.shape)

(24420,)


In [ ]:
print((y_train==0).sum())

18563


In [ ]:
print((y_train==1).sum())

5857


In [ ]:
y_train.unique()

array([1, 0])

In [ ]:
from sklearn.metrics import precision_score, recall_score, f1_score
print(precision_score(y_train,train_pred))
print(recall_score(y_train, train_pred))
print(f1_score(y_train, train_pred))

0.49845659958019506
0.6892607136759433
0.5785325308111205


In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
params=[{'penalty':['l1', 'l2', 'elasticnet']}, {'alpha':[0.001, 0.01, 0.1, 1]},
        {'eta0':[0.001,0.02, 0.3,0.5,1]}]

In [ ]:
gs=GridSearchCV(estimator=Perceptron(), param_grid=params)
gs.fit(xtrain_sc, y_train)

GridSearchCV(estimator=Perceptron(),
             param_grid=[{'penalty': ['l1', 'l2', 'elasticnet']},
                         {'alpha': [0.001, 0.01, 0.1, 1]},
                         {'eta0': [0.001, 0.02, 0.3, 0.5, 1]}])

In [ ]:
gs.best_score_

0.7990990990990992

In [ ]:
gs.best_params_

{'penalty': 'l1'}

In [ ]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(xtrain_sc, y_train)

LogisticRegression()

In [ ]:
lr_train_pred=lr.predict(xtrain_sc)
lr_test_pred=lr.predict(xtest_sc)

In [ ]:
print("Training Accuracy:", accuracy_score(lr_train_pred, y_train))
print("Testing Accuracy:", accuracy_score(lr_test_pred, y_test))

Training Accuracy: 0.8260851760851761
Testing Accuracy: 0.820292347377472


In [ ]:
confusion_matrix(lr_train_pred, y_train)

array([[17499,  3183],
       [ 1064,  2674]])

In [ ]:
from sklearn.svm import SVC
svc=SVC()
svc.fit(xtrain_sc, y_train)

SVC()

In [ ]:
svc_train_pred=svc.predict(xtrain_sc)
svc_test_pred=svc.predict(xtest_sc)
print("Training Accuracy:", accuracy_score(svc_train_pred, y_train))
print("Testing Accurcay:", accuracy_score(svc_test_pred, y_test))

Training Accuracy: 0.8574938574938575
Testing Accurcay: 0.844490848790075


In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
knn=KNeighborsClassifier()
knn.fit(xtrain_sc, y_train)

KNeighborsClassifier()

In [ ]:
knn_train_pred=knn.predict(xtrain_sc)
knn_test_pred=knn.predict(xtest_sc)
print("Training Accuracy:", accuracy_score(y_train, knn_train_pred))
print("Testing Accuracy:", accuracy_score(y_test, knn_test_pred))

Training Accuracy: 0.8782964782964783
Testing Accuracy: 0.8301191499815748


In [ ]:
k_param=[{'n_neighbors':[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]}]
knn_gs=GridSearchCV(estimator=KNeighborsClassifier(), param_grid=k_param)

In [ ]:
knn_gs.fit(xtrain_sc, y_train)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid=[{'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
                                          13, 14, 15]}])

In [ ]:
print(knn_gs.best_score_)
print(knn_gs.best_params_)


0.8327600327600327
{'n_neighbors': 11}


In [ ]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier(criterion='entropy',max_depth=6)
dt.fit(xtrain_sc, y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=6)

In [ ]:
dt_train_results=dt.predict(xtrain_sc)
dt_test_results=dt.predict(xtest_sc)
print("Training Accuracy:", accuracy_score(dt_train_results, y_train))
print("Testing Accuracy:", accuracy_score(dt_test_results, y_test))

Training Accuracy: 0.8502047502047502
Testing Accuracy: 0.8451050239528314


In [ ]:
from sklearn.ensemble import VotingClassifier

In [ ]:
vc=VotingClassifier(estimators=[('lr',LogisticRegression()),
 ('dt', DecisionTreeClassifier())], voting='hard')
vc.fit(xtrain_sc, y_train)

VotingClassifier(estimators=[('lr', LogisticRegression()),
                             ('dt', DecisionTreeClassifier())])

In [ ]:
vc_train_results=vc.predict(xtrain_sc)
vc_test_results=vc.predict(xtest_sc)
print("Training Accuracy:", accuracy_score(vc_train_results, y_train))
print("Testing Accuracy:", accuracy_score(vc_test_results, y_test))

Training Accuracy: 0.8696560196560197
Testing Accuracy: 0.8298734799164722


In [ ]:
vc.predict(xtrain_sc[[0]])

array([1])

In [ ]:
import numpy as np
y_train=np.array(y_train)
y_train[0]

1

In [ ]:
p.predict(xtrain_sc[[0]])

array([1])

In [ ]:
lr.predict(xtrain_sc[[0]])

array([1])

In [ ]:
dt.predict(xtrain_sc[[0]])

array([0])

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rfc=RandomForestClassifier(n_estimators=10)
rfc.fit(xtrain_sc, y_train)

RandomForestClassifier(n_estimators=10)

In [ ]:
rfc_train_results=rfc.predict(xtrain_sc)
rfc_test_results=rfc.predict(xtest_sc)
print("Training Accuracy:", accuracy_score(rfc_train_results, y_train))
print("Testing Accuracy:", accuracy_score(rfc_test_results, y_test))

Training Accuracy: 0.9865683865683865
Testing Accuracy: 0.8535806411988699
