<a href="https://colab.research.google.com/github/Sanjeev00001/Machine-Learning-1/blob/main/Libriaries_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
pip install numpy

In [ ]:
a=[1,2,'a',2.3]

In [ ]:
prnt(type(a))

NameError: name 'prnt' is not defined

In [ ]:
print(type(a))

<class 'list'>


In [ ]:
print(type([0]))

<class 'list'>


In [ ]:
a1=np.array(a)

In [ ]:
print(type(a1))

<class 'numpy.ndarray'>


In [ ]:
print(a1)

['1' '2' 'a']


In [ ]:
print(a)

[1, 2, 'a']


In [ ]:
len(a1)

3

In [ ]:
np.shape(a1)

(3,)

In [ ]:
a=np.array(([1,2,3][4,5,6][7,8,9]))

<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<ipython-input-14-2cdd70f192a2>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  a=np.array(([1,2,3][4,5,6][7,8,9]))


TypeError: list indices must be integers or slices, not tuple

In [ ]:
a=np.array([[1,2,3][4,5,6][7,8,9]])

<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<ipython-input-15-30e90c4c3d83>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  a=np.array([[1,2,3][4,5,6][7,8,9]])


TypeError: list indices must be integers or slices, not tuple

In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
print(np.shape(a))

(3, 3)


In [ ]:
print(len(a))

3


In [ ]:
print(np.size(a))

9


In [ ]:
=np.reshape(a,(1,9))

SyntaxError: invalid syntax (<ipython-input-20-e679e935228e>, line 1)

In [ ]:
b=np.reshape(a,(1,9))

In [ ]:
print(b)

[[1 2 3 4 5 6 7 8 9]]


In [ ]:
c=np.reshape(a,(9,1))

In [ ]:
print(c)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [ ]:
a=np.zeros((5,))

In [ ]:
print(a)

[0. 0. 0. 0. 0.]


In [ ]:
a=np.zeros((5,4),dtype='int16')

In [ ]:
print(a
      )

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
b=np.ones((4,))


In [ ]:
b

array([1., 1., 1., 1.])

In [ ]:
b=np.ones((2,3,4))

In [ ]:
b

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
b=np.ones((2,4,3))

In [ ]:
b

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
c=np.random((2,4))

TypeError: 'module' object is not callable

In [ ]:
c=np.random.random(2,4)

TypeError: random() takes at most 1 positional argument (2 given)

In [ ]:
c=np.random.random((2,4))

In [ ]:
c

array([[0.77237954, 0.18677645, 0.87108123, 0.58965812],
       [0.90365051, 0.94575622, 0.05441263, 0.35189083]])

In [ ]:
c=np.random.random((2,4),dtype='int16')

TypeError: random() got an unexpected keyword argument 'dtype'

In [ ]:
a=[1,2,3,4]
b=[5,6,7,8]

In [ ]:
c=a+b

[1, 2, 3, 4, 5, 6, 7, 8]


In [ ]:

a=np.array(a)
b=np.array(b)
c=a+b


In [ ]:
c

array([ 6,  8, 10, 12])

In [ ]:
d=a-b
e=a*b
print(d)
print(e)

[-4 -4 -4 -4]
[ 5 12 21 32]


In [ ]:
a=np.array([[1,2,3],[4,5,6],7,8,9])
b=np.array([[2,3],[4,5],[5,6]])

<ipython-input-46-83197b2f23ec>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a=np.array([[1,2,3],[4,5,6],7,8,9])


In [ ]:
c=a@b

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 5)

In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[2,3],[4,5],[5,6]])

In [ ]:
c=a*b

ValueError: operands could not be broadcast together with shapes (3,3) (3,2) 

In [ ]:
c=a@b

In [ ]:
print(c)

[[ 25  31]
 [ 58  73]
 [ 91 115]]


In [ ]:
c1=np.dot(a,b)

In [ ]:
print(c1)

[[ 25  31]
 [ 58  73]
 [ 91 115]]


In [ ]:
np.mod(10,2)

0

In [ ]:
a=np.arange(1,9,3)

In [ ]:
print(a)

[1 4 7]


In [ ]:
a=np.linespace(1,10,10)

AttributeError: module 'numpy' has no attribute 'linespace'

In [ ]:
a=np.linspace(1,10,10)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
