<a href="https://colab.research.google.com/github/Sanjeev00001/Machine-Learning-1/blob/main/Python_libraries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hellow")

hellow


In [ ]:
a=2
b=4
c=a+b
print(c)

6


In [ ]:
import numpy as np

In [ ]:
a=int(input("enter the value of a "))
b=int(input("enter the values of b "))
c=a+b
print(c)
d=a-b
print(d)
e=a*b
print(e)



enter the value of a 1
enter the values of b 3
4
-2
3


In [ ]:
x=np.array([[1],[2],[3]])
print(x)

[[1]
 [2]
 [3]]


In [ ]:
x.shape

(3, 1)

In [ ]:
## vector addition


In [ ]:
y=np.array([[2],[3],[4]])

In [ ]:
print(y)

[[2]
 [3]
 [4]]


In [ ]:
vector_sum=x+y

In [ ]:
print(vector_sum)

[[3]
 [5]
 [7]]


In [ ]:
np.add(x,y)

array([[3],
       [5],
       [7]])

In [ ]:
aa=np.add(y,x)

In [ ]:
print(aa)

[[3]
 [5]
 [7]]


In [ ]:
a=2
np.add(x,2)

array([[3],
       [4],
       [5]])

In [ ]:
## vectoe scalar multiplication
a=2
a*y

array([[4],
       [6],
       [8]])

In [ ]:
## linear combination of vector
a,b=2,3
a*x+b*y

array([[ 8],
       [13],
       [18]])

In [ ]:
## linear combination of vector
a,b=2,3
x,y = np.array([[2],[3]]),np.array([[4],[5]])
a*x+b*y

array([[16],
       [21]])

In [ ]:
## vector-vector multiplication


In [ ]:
x,y = np.array([[-2],[2]]),np.array([[4],[-3]])
dot_product=x.T@y

In [ ]:
np.dot(x.T,y)

array([[23]])

In [ ]:
x,y = np.array([[-2],[2]]),np.array([[4],[-3]])
dot_product=x.T@y

In [ ]:
print(dot_product)

[[-14]]


In [ ]:
np.dot(x.T,y)

array([[-14]])

In [ ]:
#Eucleadin norm L2 and norm
x=np.array([[3],[4]])
np.linalg.norm(x,2)

5.0

In [ ]:
# Manhattan norm  L1 normy
x=np.array([[3],[-4]])
np.linalg.norm(x,1)

7.0

In [ ]:
# Max norm infinity norm
x=np.array([[3],[-4]])
np.linalg.norm(x,np.inf)

4.0

In [ ]:
# to find distance
x,y=np.array([[-2],[2]]),np.array([[4],[-3]])
distance=np.linalg.norm(x-y,2)

In [ ]:
print(distance)

6.0827625302982185


In [ ]:
# VECTOR ANGLES AND AOTHOGONALITY
x=np.array([[1],[2]])
y=np.array([[5],[7]])
cos_theta=(x.T@y)/(np.linalg.norm(x,2)*np.linalg.norm(y,2))

In [ ]:
print(cos_theta)

[[0.98776297]]


In [ ]:
cos_inv = np.arccos(cos_theta)

In [ ]:
print(cos_inv)
# this is in radians

[[0.15660188]]


In [ ]:
#conver to radiand to degrees
degree = (180/np.pi)*(cos_inv)

In [ ]:
print(degree)

[[8.97262661]]


In [ ]:
# system of linear equations

# x+2y = 8
# 5x-3y=1

A=np.array([[0,2] # 1st row
            ,[1,4]])#2nd row

In [ ]:
print(A)

[[0 2]
 [1 4]]


In [ ]:
A.shape

(2, 2)

In [ ]:
B=np.array([[3,1],#1at row
           [-3,2]]) # 2nd row

In [ ]:
print(B)

[[ 3  1]
 [-3  2]]


In [ ]:
A+B

array([[ 3,  3],
       [-2,  6]])

In [ ]:
alpha = 2
alpha*2

4

In [ ]:
alpha*A

array([[0, 4],
       [2, 8]])

In [ ]:
np.multiply(alpha,A)

array([[0, 4],
       [2, 8]])

In [ ]:
# Matrix vector multiplication
A @ x

array([[4],
       [9]])

In [ ]:
np.dot(A,x)

array([[4],
       [9]])

In [ ]:
A@B

array([[-6,  4],
       [-9,  9]])